# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc495a1e550ae7861dc3ff132978ebbe8d8d63997e0f6edfed970fdeb7f8388eb12043b5e9154ab9908a73dfdb69cc4ec0b1be287392dd3b756cf50bc4422dbc

test:
  secret_key_base: 7c6486a26c05c55f1aedf53ed94dd9ad29d2009f53a75d1382acd6d86a6daf96bd9ef9d5776e8a3514fafc68b93ffb9f64d85bb8304a788055c2306a60a929d1

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
